### ISSUE TITLE
DesktopSharing 问题询问

### ISSUE THREAD

**Issue by tdf5843** [PHZ76/DesktopSharing#10]
Hi PHZ76,

您好，我是来自台湾的工程师 William
我在GitHub上看到您DesktopSharing的专案
有几个问题想跟您请益，若您方便的话，就烦请您指导了
我才刚开始研究DXGI与RTSP不久，如果有什么问得不清楚的还请您见谅

1. 目前在DXGI + RTSP的这个架构下，就算我把VLC的network-caching的值改为0，还是会有些许的延迟(0.3s~0.5s)，如下图
这个部分是架构上的限制导致的吗? 或是还有机会可以改善?
不知道您有没有什么建议的方向(例如:从nvenc或是从RTSP方面着手)，因为我想针对这个部分去研究，让延迟能再低一点
![Outlook-1suxc520](https://user-images.githubusercontent.com/8804780/67743643-3da90b00-fa5a-11e9-920c-a8c397404987.png)

2. 您在code里面有进行FPS的统计，我也有更改avconfig.framerate的数值为120，输出的FPS确实有改变
但是，若我使用手机的VLC播放器，并用Gamebench去测试FPS，却仅能跑到60的FPS
这个会是因为手机版本的VLC所导致吗? 还是手机硬体的影响(我使用ASUS Zenfone3)?
不知道您有没有什么建议的方向可以让我去Debug?
![thumbnail_Outlook-5g2wwvsu](https://user-images.githubusercontent.com/8804780/67743715-6f21d680-fa5a-11e9-8ebf-8785278afea8.png)
![Outlook-mqcufxux](https://user-images.githubusercontent.com/8804780/67743710-6c26e600-fa5a-11e9-8271-98316d5e2946.png)

因为我不太会简体中文，文字内容是翻译的结果，如果有用词不精确的部分还望你海涵

**Comment by PHZ76** [comment]
你好，对于你目前遇到的问题我说下我的看法，希望能帮到你。

1. 客户端显示延时问题。视频采集，编码，传输，解码和显示，这个几个环节产生延时最大模块一般是视频编码，其次是解码，一般使用硬件编码配合软件解码也可以做到100ms的延时。 VLC和ffplay在设置为无缓冲的状态下还是会有200ms以上的延时，如果想要实现低延时的应用，播放器必须自己实现，我以前用过dxva2和qsv解码并显示，画面显示延时在100ms以下。

2. 帧率问题。一般应用在60帧就已经足够了，帧率太高，客户端硬件性能不够也处理不过来。我这边目前硬件资源有限，只测试了60帧。对于图中显示60帧的问题，我猜测是跟屏幕的刷新率有关，有些播放器也会做垂直同步。

**Comment by tdf5843** [comment]
非常感谢您的协助
我会再针对这几个部份去研究，感谢
