### ISSUE TITLE
客户端播放延迟越来越高，刷新一下就好了

### ISSUE THREAD

**Issue by setsuna** [PHZ76/DesktopSharing#11]
另外客户端解码GPU占用率很高，丢帧率高造成画面卡顿。 刚开始学不知道为，希望大佬能够解答。

**Comment by setsuna** [comment]
试了下新的图片是花的
![1](https://user-images.githubusercontent.com/483610/68271692-5a69c200-009c-11ea-9669-36aee797ac9c.png)

**Comment by PHZ76** [comment]
这个像是客户端渲染的问题，不要使用太高的帧率，试试VLC？

**Comment by setsuna** [comment]
测试vlc是好的 我用的是 https://www.hlsplayer.net/rtmp-player 这个测试播放器 VLC延迟太高了 跟帧率好像没什么关系

**Comment by PHZ76** [comment]
这个播放器我这边打不开，要科学上网？走外网要注意带宽问题，码率调低点试试
