### ISSUE TITLE
如果要抓屏兼容win7，要怎么操作？

### ISSUE THREAD

**Issue by jonnykay** [PHZ76/DesktopSharing#13]
如果抓屏要兼容win7的话，是不是可以用ffmpeg的抓屏方法gdigrab来代替dxgi，但是用gdigrab取到的数据怎么处理呢？

**Comment by gerryhjs** [comment]
dxgi.dll的依赖理论上可以通过把dll拷贝到工程目录的方式解决。你可以测一下

**Comment by jonnykay** [comment]
> dxgi.dll的依赖理论上可以通过把dll拷贝到工程目录的方式解决。你可以测一下

是直接把这个dxgi.dll这个文件拷贝到运行的程序根目录吗？

**Comment by PHZ76** [comment]
dxgi只能在win8系统上使用，不是拷贝dll就能解决的。win7 一般是用 DirectX 或 mirror driver，选一个方案，重新实现抓屏模块。

**Comment by gerryhjs** [comment]
可以尝试这样一个思路：AVInputFormat *ifmt = av_find_input_format("gdigrab");(avformat_open_input(&pFormatCtx_Video, "desktop", ifmt, &options)；
