### ISSUE TITLE
关于pushVideo

### ISSUE THREAD

**Issue by o-u-p** [PHZ76/DesktopSharing#15]
if (pkt->data[4] == 0x65 || pkt->data[4] == 0x6)
大神， 这里为什么sei也要加sps啊？

**Comment by PHZ76** [comment]
不是给SEI加SPS，是给关键帧加SPS

**Comment by o-u-p** [comment]
后面为啥要或上SEI啊, 可以讲解一下么， 似乎也是当成关键帧来处理的。

**Comment by PHZ76** [comment]
因为这里的关键帧前面带了SEI，我只能这样判断它是不是关键帧，有没有SEI不是重点。SEI是NV的编码器加的
