### ISSUE TITLE
声音采集用的WASAPI, win10上面不能用

### ISSUE THREAD

**Issue by o-u-p** [PHZ76/DesktopSharing#16]
win10上面需要怎么操作呢

**Comment by PHZ76** [comment]
wasapi 在win10也可以用的，可以提供下其他信息或接口调用失败的信息吗

**Comment by o-u-p** [comment]
我把音视频数据写到文件里了， 似乎是音频只能抓一些应用的声音， 不能抓人说话的声音。
[run-env.zip](https://github.com/PHZ76/DesktopSharing/files/3998666/run-env.zip)

**Comment by PHZ76** [comment]
是的，因为人输入的声音是通过麦克风的，这里是抓声卡的声音，如果要同时听到人的声音和应用的声音，需要把麦克风和声卡这两路音频同时采集，并做混音处理合为一路音频，这个我目前没有做。

**Comment by PHZ76** [comment]
是的，因为人的声音是通过麦克风采集的，这里是抓声卡的声音，如果要同时听到人和应用的声音，需要把麦克风和声卡这两路音频同时采集，并做混音处理合为一路音频，这个我目前没有做。

**Comment by o-u-p** [comment]
但是这个声音放出来很刺耳，有点像锯齿的声音。。。
