### ISSUE TITLE
大哥，能不能打个软件包发给我

### ISSUE THREAD

**Issue by duhengxiao** [PHZ76/DesktopSharing#2]
我是java开发，目前在找推流的工具，你这个好像很符合我的需求。
so...能不能直接编译个exe可执行的文件给我，感谢！
我的邮箱是 duhengxiao@163.com

**Comment by PHZ76** [comment]
抱歉，现在才看到。我这个项目只是个demo，如果要在实际项目中使用，我建议还是要找一些成熟的开源项目
