### ISSUE TITLE
请问为什么不直接使用FFmpeg 带 NVIDIA Video Hardware Acceleration 的版本?

### ISSUE THREAD

**Issue by xfirefly** [PHZ76/DesktopSharing#20]
而要单独使用nvidia-video-codec-sdk , 看nvidia官网说ffmpeg 直接支持硬件编码?

**Comment by PHZ76** [comment]
你好，因为FFmpeg提供的接口需要从内存传入图像，如果图像是在显存中，则需要拷贝到内存才可以使用。使用原生的SDK可以直接传入texture，直接编码，不需要拷贝到内存，效率更高。

**Comment by xfirefly** [comment]
Thanks a lot.
