### ISSUE TITLE
局域网播放延时问题

### ISSUE THREAD

**Issue by xfirefly** [PHZ76/DesktopSharing#21]
谢谢作者的开源代码, 我尝试用该库作为发送端, 接收端用ffmpeg  播放, 延时比较高, 如果要降低延时, 请问该从哪方面入手?  
用rtp over udp 理论上有没有可能改善? 非常感谢

**Comment by PHZ76** [comment]
你好，如果要降低延时，最好是使用硬件编码，客户端不要缓冲，自己实现解码和渲染，这套流程在局域网内基本在100ms以下了。

**Comment by xfirefly** [comment]
谢谢, 目前用的软编, tcp nodelay 发送视频流, 局域网在200ms  左右
