### ISSUE TITLE
HTTP Streaming

### ISSUE THREAD

**Issue by symisc** [PHZ76/DesktopSharing#23]
Hello.

Is it possible to stream directly to a HTTP server located somewhere via HLS or RTMP proxy, etc. Basically, we want each streamer to broadcast his desktop to his audience via a web browser something like Youtube.

**Comment by PHZ76** [comment]
Hi,  you need a media server convert the protocol，I recommend using node-media-server.

https://github.com/illuspas/Node-Media-Server

**Comment by symisc** [comment]
Do you a instructions guide on how to glue all of this. Thanks.
