### ISSUE TITLE
rtsp推流好像不支持udp

### ISSUE THREAD

**Issue by vjeson** [PHZ76/DesktopSharing#27]
使用第三方的rstp服务器，rtsp推流不成功，服务本身没有问题支持udp推流

**Comment by PHZ76** [comment]
你好。是的，目前的RTSP推流器，我只实现了TCP推流，还没有做UDP推流。如果有需要可以尝试使用FFmpeg来做推流。

**Comment by vjeson** [comment]
好的，多谢，请教抓屏的时候能否实现webrtc里面，chrome实现的按照窗口，程序方式，或者指定抓取某个屏幕？
![share](https://user-images.githubusercontent.com/2101082/88257904-6ca29380-ccf1-11ea-88e0-d95806c3cdec.png)

**Comment by PHZ76** [comment]
webrtc 这种事抓窗，我目前没有实现。如果想抓取屏幕某块区域，直接调整DXGI抓屏模块的参数就好了
