### ISSUE TITLE
在1860*1050分辨率的电脑测试码流是花屏的

### ISSUE THREAD

**Issue by 123pzb** [PHZ76/DesktopSharing#29]
int DXGIScreenCapture::AquireFrame()函数里面的
hr = d3d11_context_->Map(rgba_texture_.Get(), 0, D3D11_MAP_READ, 0, &dsec);
	if (!FAILED(hr)) {
		if (dsec.pData != NULL) {
			image_ptr_.reset(new uint8_t[image_size_]);
			memcpy(image_ptr_.get(), dsec.pData, image_size_);//这一行有问题	
		}
		d3d11_context_->Unmap(rgba_texture_.Get(), 0);
	}

memcpy(image_ptr_.get(), dsec.pData, image_size_);应该改为
for (int y = 0; y < GetHeight(); y++)
{
	memcpy(image_ptr_.get() + y * GetWidth() * 4, (uint8_t *)dsec.pData + y * dsec.RowPitch, GetWidth() * 4);
}

**Comment by 123pzb** [comment]
void ScreenLive::EncodeVideo()里面
memcpy((uint8_t *)map.pData, &bgra_image[0], bgra_image.size());
需要改为
for (int y = 0; y < height; y++)
{
	memcpy((uint8_t *)map.pData + y * map.RowPitch, &bgra_image[0] + y * width * 4, width * 4);
}

**Comment by PHZ76** [comment]
是的，我这里写的有问题。非常感谢你帮我修复这个问题 。
