### ISSUE TITLE
cpu占用率过高等问题

### ISSUE THREAD

**Issue by ttfft** [PHZ76/DesktopSharing#3]
你好，我正在学习推流，看了你的代码对我帮助非常大；折腾的时候发现你的demo比OBS、ffmpeg推屏幕内存，cpu占用过高，目前没发现是哪里的问题，望大神不吝赐教，谢谢。
memory 250MB左右
cpu 50%
i7 2.4g/ 8g /64位/windos10 vs2017 / 
1716353147@qq.com

**Comment by PHZ76** [comment]
这只是我为了方便调试RTSP-Server写的demo，没有考虑过CPU内存占用等问题，跟OBS这些没得比啊。CPU占用率高主要是在视频编码这一块。
