### ISSUE TITLE
无法与EasyDarwin对接的问题。

### ISSUE THREAD

**Issue by 76810490** [PHZ76/DesktopSharing#4]
正在学习推流的代码，Demo对我的帮助很大。但在学习的过程中，
1）发现不能与EasyDar对接，即Web后台看流列表中，看不到。是不是easyDar 我没配置好。
2）还有就是在本地转发的，然后用VLC来看的时候，会有花屏的问题。
PC：W10 LTSC，CPU-I5-2.2G，内存：12G，VS2015
EasyDar版本：Server: EasyDarwin/7.3 (Build/17.0325; Platform/Win32; Release/EasyDarwin; State/Development; )

**Comment by PHZ76** [comment]
1. EasyDarwin 不需要做配置，如果不确定可以使用ffmpeg推流文件试试服务器是否正常运行。
2. 使用本地转发，每次调用pushframe需要确保传入完整的一帧。
3. 尝试降低视频编码的帧率。
4. 建议先调好本地转发的效果再调试推流，发起推流后可以wireshark抓包看看和服务器的RTSP交互是否正常。
