### ISSUE TITLE
你好，编译后使用vlc打开失败

### ISSUE THREAD

**Issue by xoraxrax** [PHZ76/DesktopSharing#6]
```
DesktopSharing::instance().startRtspServer("live", 8554);
```

![image](https://user-images.githubusercontent.com/27957496/63341593-2673e000-c37c-11e9-92f6-8ed528dc9caa.png)

**Comment by PHZ76** [comment]
rtsp url的ip使用你本机的ip 不要使用 ”0.0.0.0“

**Comment by xoraxrax** [comment]
可以了 就是有点延时 👍

**Comment by PHZ76** [comment]
有延时可以调小VLC的缓冲区为200ms

**Comment by xoraxrax** [comment]
有用 多谢😄
